--insert into Users (login_id, password, nickname, role) values ('123', '123', '123', 'USER');
--insert into Board (title, text, board_status) values ('title1', 'text1', 'WAIT');
--insert into Board (title, text, board_status) values ('title2', 'text2', 'WAIT');